on:
  push:
    branches:
      - main
  pull_request:

name: ci

jobs:
  build_and_test:
    name: UoIndexer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Install cargo-sort
        run: |
          cargo install cargo-sort
      
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Lint
        run: |
          cargo clippy

      - name: Build
        run: |
          cargo build
